#!/bin/sh
mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mkdir -m 1777 -p /dev/shm
mount -a        # Mount everything from /etc/fstab

